import React from "react";
export const data =
  [
       {
          id: 1,
          thumb: '../jpg/JS_back-end.jpg',
          title: 'Javascript',
          title2: 'js',
          img1: '../jpg/fundamentos-js-variaveis.jpg',
          img2: '../jpg/fundamentos-js-arrays.jpg',
          img3: '../jpg/fundamentos-js-objetos.jpg',
          img4: '../jpg/JS_inicio.jpg',
          img5: '../jpg/JS_back-end.jpg',
          img6: '../jpg/JS_herança.jpg',
          img7: '../jpg/JS_orientacao_a_objetos.jpg',
          img8: '../jpg/JS_web.jpg',
          img9: '../jpg/JS.jpg',
          img10:'../jpg/Typescript_1.jpg',
          img11:'../jpg/Typescript_2.jpg'
        },
        {
          id: 2,
          thumb: '../jpg/React_JS.jpg',
          title: 'React',
          title2: 'React',
          img1: '../jpg/React_ciclo_de_vida.jpg',
          img2: '../jpg/React_components.jpg',
          img3: '../jpg/React_funcionamento.jpg',
          img4: '../jpg/React_function.jpg',
          img5: '../jpg/React_hooks.jpg',
          img6: '../jpg/React_JS.jpg',
          img7: '../jpg/React_router.jpg',
          img8: '../jpg/React_testes.jpg',
        },
        {
          id: 3,
          thumb: '../jpg/HTML5_e_CSS3_4.jpg',
          title: 'Html & Css',
          title2: 'React',
          img1: '../jpg/HTML5_e_CSS3_1.jpg',
          img2: '../jpg/HTML5_e_CSS3_2.jpg',
          img3: '../jpg/HTML5_e_CSS3_3.jpg',
          img4: '../jpg/HTML5_e_CSS3_4.jpg',
          img5: '../jpg/arquitetura_css.jpg',
          img6: '../jpg/bootstrap_4.jpg',
          img7: '../jpg/css_grid.jpg',
          img8: '../jpg/flexbox.jpg'
        },
        {
          id: 4,
          thumb: '../jpg/Blender.jpg',
          title: 'Others',
          title2: 'Others',
          img1: '../jpg/Acessibilidade_web.jpg',
          img2: '../jpg/Acessibilidade_web_1.jpg',
          img3: '../jpg/Blender.jpg',
          img4: '../jpg/dart.jpg', 
          img4: '../jpg/git_e_github.jpg',
          img5: '../jpg/HTTP.jpg',
          img6: '../jpg/Linux.jpg',
          img7: '../jpg/Logica_de_programacao.jpg',
          img8: '../jpg/Logica_de_programacao_2.jpg',
          img9: '../jpg/Rest_com_nodeJS.jpg',
        }
  ]